apiVersion: v1
kind: Service
metadata:
  name: disney-app
  labels:
    app: disney-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30005
  selector:
    app: disney-app
